My Application: Dweller Class Reference
Dweller Class Reference
#include <Dweller.h>
Public Member Functions
Dweller (const string &name="", const int &count=0)
Default constructor for class Dweller. Constructor for the class Dweller used when a Dweller object is created.
virtual ~Dweller ()
Default Destructor for class Dweller.
const int getSPECIAL ()
returns special
const int getCurrentHealth ()
Returns Dweller Current health.
const int getCurrentRadDamage ()
returns radiation
const int getAttackDmg ()
returns the amount of attack damage a Dweller has
void setPosition (const Vec2D &position)
set the postion of dweller
const Vec2D getPosition ()
returns the dweller position
void receiveHealthDamage (const int &health)
damages the Dweller
void receiveRadDamage (const int &health)
increases amount of radiation
void receiveEquipmentDamage (const int &durability)
damages the equipments
void addStimpak (const int &stimpak)
add the amount of simpak
void addRadAway (const int &radiation)
gain one radaway
void useStimpak ()
use one stimpak
void useRadAway ()
uses one radaway
Outfit * assignOutfit (Outfit *outfit)
Sets an Outfit.
Weapon * assignWeapon (Weapon *weapon)
Sets an Weapon.
bool isDead ()
Checks if a Dweller is dead.
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Default Destructor for class GameObject Constructor for the class GameObject used when a GameObject object is Destroyed.
string getName ()
Returns the name of the GameObject.
Private Attributes
Vec2D position_
int SPECIAL_
int health_
int radiation_
int stimpak_
int radAway_
Outfit * outfit_
Weapon * weapon_
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Returns the name of the GameObject.
Protected Member Functions inherited from GameObject
GameObject (const string &name="")
Default constructor for class GameObject Constructor for the class GameObject used when a GameObject object is created.
Detailed Description
Definition at line 25 of file Dweller.h.
Constructor & Destructor Documentation
Dweller::Dweller (const string & name = "", const int & SPECIAL = 0)
Default constructor for class Dweller. Constructor for the class Dweller used when a Dweller object is created.
Returns
Nothing
Definition at line 30 of file Dweller.cpp.
Dweller::~Dweller () virtual
Default Destructor for class Dweller.
Parameters
rhs Destructor for the class Dweller used when a Dweller object is created
Returns
Nothing
Definition at line 61 of file Dweller.cpp.
Member Function Documentation
void Dweller::addRadAway (const int & radAway)
gain one radaway
Parameters
radaway a consumeable Item
Returns
nothing
Definition at line 332 of file Dweller.cpp.
References radAway_.
Referenced by testNames().
void Dweller::addStimpak (const int & stimpak)
add the amount of simpak
Parameters
Stimpak an Item
Returns
nothing
Definition at line 312 of file Dweller.cpp.
References stimpak_.
Referenced by testNames().
Outfit * Dweller::assignOutfit (Outfit * outfit)
Sets an Outfit.
Parameters
outfit Outfit is an Item that gives a Dweller special;
Returns
the old equipped Outfit
Definition at line 391 of file Dweller.cpp.
References outfit_.
Referenced by main(), and testNames().
Weapon * Dweller::assignWeapon (Weapon * weapon)
Sets an Weapon.
Parameters
Weapon Weapon is an Item that gives a Dweller attack;
Returns
the old equipped Weapon
Definition at line 413 of file Dweller.cpp.
References weapon_.
Referenced by testNames().
const int Dweller::getAttackDmg ()
returns the amount of attack damage a Dweller has
Parameters
attackDamage the amount of damage a Dweller has
Returns
damage
Definition at line 176 of file Dweller.cpp.
References Weapon::getAttackDmg(), and weapon_.
Referenced by testNames().
const int Dweller::getCurrentHealth ()
Returns Dweller Current health.
Parameters
rhs retrieves current health of dweller
Returns
health_
Definition at line 133 of file Dweller.cpp.
References health_.
Referenced by isDead(), and testNames().
const int Dweller::getCurrentRadDamage ()
returns radiation
Parameters
radiation amount of damage you take from Radiation
Returns
radiation_
Definition at line 155 of file Dweller.cpp.
References radiation_.
Referenced by testNames().
const Vec2D Dweller::getPosition ()
returns the dweller position
Parameters
position current Position of a Dweller
Returns
position_
Definition at line 225 of file Dweller.cpp.
References position_.
Referenced by testNames().
const int Dweller::getSPECIAL ()
returns special
Parameters
rhs Calculates the total special
Returns
special_
Definition at line 82 of file Dweller.cpp.
References Outfit::getSPECIAL(), outfit_, and SPECIAL_.
Referenced by main(), and testNames().
bool Dweller::isDead ()
Checks if a Dweller is dead.
Parameters
currentHealth The health of a Dweller
Returns
the old equipped outfit
Definition at line 436 of file Dweller.cpp.
References getCurrentHealth().
Referenced by testNames().
void Dweller::receiveEquipmentDamage (const int & durability)
damages the equipments
Parameters
durability the durability of a Weapon / Outfit
Returns
nothing
Definition at line 288 of file Dweller.cpp.
References outfit_, Weapon::receiveDamage(), Outfit::receiveDamage(), and weapon_.
Referenced by testNames().
void Dweller::receiveHealthDamage (const int & health)
damages the Dweller
Parameters
health amount of health a Dweller has
Returns
nothing
Definition at line 246 of file Dweller.cpp.
References health_.
Referenced by testNames().
void Dweller::receiveRadDamage (const int & radiation)
increases amount of radiation
Parameters
radiation the dama
Returns
nothing
Definition at line 268 of file Dweller.cpp.
References radiation_.
Referenced by testNames().
void Dweller::setPosition (const Vec2D & position)
set the postion of dweller
Parameters
position the position that is going to be set for the Dweller
Returns
nothing
Definition at line 204 of file Dweller.cpp.
References position_.
Referenced by testNames().
void Dweller::useRadAway ()
uses one radaway
Parameters
radiation the amount of damage a dweller takes from radiation
Returns
nothing
Definition at line 371 of file Dweller.cpp.
References radiation_.
Referenced by testNames().
void Dweller::useStimpak ()
use one stimpak
Parameters
Stimpak it is a consumeable Item
Returns
nothing
Definition at line 351 of file Dweller.cpp.
References health_.
Referenced by testNames().
Field Documentation
int Dweller::health_ private
Definition at line 63 of file Dweller.h.
Referenced by getCurrentHealth(), receiveHealthDamage(), and useStimpak().
Outfit* Dweller::outfit_ private
Definition at line 67 of file Dweller.h.
Referenced by assignOutfit(), getSPECIAL(), and receiveEquipmentDamage().
Vec2D Dweller::position_ private
Definition at line 61 of file Dweller.h.
Referenced by getPosition(), and setPosition().
int Dweller::radAway_ private
Definition at line 66 of file Dweller.h.
Referenced by addRadAway().
int Dweller::radiation_ private
Definition at line 64 of file Dweller.h.
Referenced by getCurrentRadDamage(), receiveRadDamage(), and useRadAway().
int Dweller::SPECIAL_ private
Definition at line 62 of file Dweller.h.
Referenced by getSPECIAL().
int Dweller::stimpak_ private
Definition at line 65 of file Dweller.h.
Referenced by addStimpak().
Weapon* Dweller::weapon_ private
Definition at line 68 of file Dweller.h.
Referenced by assignWeapon(), getAttackDmg(), and receiveEquipmentDamage().
The documentation for this class was generated from the following files:
Data Struct Assignment 1/Dweller.h
Data Struct Assignment 1/Dweller.cpp