My Application: Data Struct Assignment 1/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "Dweller.h"
#include "Outfit.h"
#include "Weapon.h"
#include "Item.h"
#include "GameObject.h"
#include "Vec2D.h"
Functions
void testNames ()
void shouldNotCompile ()
int main ()
Function Documentation
int main ()
Definition at line 15 of file main.cpp.
References Dweller::assignOutfit(), Dweller::getSPECIAL(), shouldNotCompile(), and testNames().
void shouldNotCompile ()
Definition at line 76 of file compileCheck.cpp.
Referenced by main().
void testNames ()
Definition at line 11 of file compileCheck.cpp.
References Dweller::addRadAway(), Dweller::addStimpak(), Dweller::assignOutfit(), Dweller::assignWeapon(), Dweller::getAttackDmg(), Weapon::getAttackDmg(), GameObject::getCount(), Dweller::getCurrentHealth(), Dweller::getCurrentRadDamage(), Item::getDurability(), Dweller::getPosition(), Dweller::getSPECIAL(), Outfit::getSPECIAL(), Dweller::isDead(), Item::receiveDamage(), Weapon::receiveDamage(), Outfit::receiveDamage(), Dweller::receiveEquipmentDamage(), Dweller::receiveHealthDamage(), Dweller::receiveRadDamage(), Dweller::setPosition(), Dweller::useRadAway(), and Dweller::useStimpak().
Referenced by main().